/**
 * Generates the parity fixtures the Python training pipeline checks itself
 * against, and asserts they are self-consistent.
 *
 * Written as a test rather than a standalone script so the fixtures cannot go
 * stale: any change to normalization regenerates them on the next `npm test`,
 * and `training/test_parity.py` then fails until the Python is updated to match.
 * The TypeScript is the source of truth because it is what runs at inference.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { handSpan, normalizeHand } from '@/features/normalize';
import { resampleWindow, PER_FRAME_DIM } from '@/features/window';
import type { Point3 } from '@/vision/types';

const OUT = resolve(process.cwd(), 'training/fixtures/normalize.json');

function hand(scale: number, originX: number, originY: number, rotation = 0): Point3[] {
  const template: [number, number][] = [
    [0, 0],
    [-0.3, -0.2], [-0.5, -0.45], [-0.62, -0.65], [-0.7, -0.82],
    [-0.25, -0.9], [-0.28, -1.35], [-0.3, -1.6], [-0.32, -1.85],
    [0, -1], [0, -1.5], [0, -1.78], [0, -2.05],
    [0.25, -0.95], [0.3, -1.4], [0.32, -1.66], [0.34, -1.9],
    [0.48, -0.85], [0.56, -1.2], [0.6, -1.42], [0.63, -1.62],
  ];
  const cos = Math.cos(rotation);
  const sin = Math.sin(rotation);
  return template.map(([x, y]) => ({
    x: originX + (x * cos - y * sin) * scale,
    y: originY + (x * sin + y * cos) * scale,
    z: 0,
  }));
}

const toArrays = (points: Point3[]) => points.map((p) => [p.x, p.y, p.z]);

describe('parity fixtures', () => {
  it('generates fixtures for training/test_parity.py', () => {
    const cases = [
      { name: 'upright-right', points: hand(0.1, 0.5, 0.8), handedness: 'Right' as const, aspect: 1 },
      { name: 'small-right', points: hand(0.04, 0.2, 0.3), handedness: 'Right' as const, aspect: 1 },
      { name: 'rotated-right', points: hand(0.1, 0.5, 0.5, 0.7), handedness: 'Right' as const, aspect: 1 },
      { name: 'widescreen', points: hand(0.1, 0.5, 0.5), handedness: 'Right' as const, aspect: 16 / 9 },
      {
        name: 'left-mirrored',
        points: hand(0.1, 0.5, 0.8).map((p) => ({ ...p, x: 1 - p.x })),
        handedness: 'Left' as const,
        aspect: 1,
      },
    ];

    const rampFrames = Array.from({ length: 7 }, (_, i) =>
      Array.from({ length: PER_FRAME_DIM }, () => i / 6),
    );

    const fixtures = {
      generatedBy: 'tests/fixtures.test.ts',
      note: 'Do not edit by hand. Regenerated by `npm test`.',
      normalizeHand: cases.map((c) => ({
        name: c.name,
        input: toArrays(c.points),
        handedness: c.handedness,
        aspect: c.aspect,
        mirrorLeft: true,
        canonicalRotation: true,
        expected: toArrays(
          normalizeHand(c.points, c.handedness, { aspect: c.aspect }),
        ),
      })),
      handSpan: cases.map((c) => ({
        name: c.name,
        input: toArrays(c.points),
        expected: handSpan(c.points),
      })),
      resampleWindow: [
        {
          name: 'ramp-7-to-16',
          input: rampFrames,
          target: 16,
          expected: chunk(
            [...resampleWindow(rampFrames.map((f) => Float32Array.from(f)), 16)],
            PER_FRAME_DIM,
          ),
        },
      ],
    };

    mkdirSync(dirname(OUT), { recursive: true });
    writeFileSync(OUT, `${JSON.stringify(fixtures, null, 2)}\n`);

    expect(fixtures.normalizeHand).toHaveLength(cases.length);
    // Every fixture must round-trip through the very function it pins.
    for (const c of fixtures.normalizeHand) {
      const points = c.input.map(([x, y, z]) => ({ x, y, z }));
      const again = toArrays(normalizeHand(points, c.handedness, { aspect: c.aspect }));
      expect(again).toEqual(c.expected);
    }
  });
});

function chunk(values: number[], size: number): number[][] {
  const out: number[][] = [];
  for (let i = 0; i < values.length; i += size) out.push(values.slice(i, i + size));
  return out;
}
