"""Check that normalize.py agrees with src/features/normalize.ts.

Run this before every training run. If it fails, fix the Python — the
TypeScript is what runs at inference time, so it is the source of truth.

    python test_parity.py

Fixtures live in fixtures/normalize.json and are generated by:

    npm run gen:fixtures
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

from normalize import hand_span, normalize_hand, resample_window

FIXTURES = Path(__file__).parent / "fixtures" / "normalize.json"
TOLERANCE = 1e-6


def main() -> int:
    if not FIXTURES.exists():
        print(f"No fixtures at {FIXTURES}.")
        print("Generate them from the TypeScript with:  npm run gen:fixtures")
        return 1

    cases = json.loads(FIXTURES.read_text())
    failures = 0

    for case in cases["normalizeHand"]:
        landmarks = np.array(case["input"], dtype=np.float64)
        actual = normalize_hand(
            landmarks,
            handedness=case.get("handedness", "Right"),
            aspect=case.get("aspect", 1.0),
            mirror_left=case.get("mirrorLeft", True),
            canonical_rotation=case.get("canonicalRotation", True),
        )
        expected = np.array(case["expected"], dtype=np.float64).reshape(21, 3)
        difference = float(np.abs(actual - expected).max())
        if difference > TOLERANCE:
            print(f"FAIL normalizeHand[{case['name']}]: max difference {difference:.3e}")
            failures += 1

    for case in cases.get("handSpan", []):
        landmarks = np.array(case["input"], dtype=np.float64)
        actual = hand_span(landmarks)
        if abs(actual - case["expected"]) > TOLERANCE:
            print(f"FAIL handSpan[{case['name']}]: {actual} != {case['expected']}")
            failures += 1

    for case in cases.get("resampleWindow", []):
        frames = np.array(case["input"], dtype=np.float32)
        actual = resample_window(frames, case["target"])
        expected = np.array(case["expected"], dtype=np.float32)
        difference = float(np.abs(actual - expected).max())
        if difference > 1e-5:
            print(f"FAIL resampleWindow[{case['name']}]: max difference {difference:.3e}")
            failures += 1

    total = (
        len(cases["normalizeHand"])
        + len(cases.get("handSpan", []))
        + len(cases.get("resampleWindow", []))
    )
    if failures:
        print(f"\n{failures}/{total} parity checks failed.")
        print("Feature extraction differs between training and inference. Do not train.")
        return 1

    print(f"All {total} parity checks passed. Training and inference agree.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
